language: php
sudo: required

php:
  - 7.2
git:
  depth: false

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
      COMPOSER_MEMORY_LIMIT=-1
addons:
  apt:
    packages:
      - docker-ce


# Cache Composer, NPM & Drush directories.
cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.npm
    - $HOME/.drush/cache

# Setup the environment.
before_install:
  # Be sure no mails are going out by disabling sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Upgrade docker compose.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  # Ensure the project is creatable with the latest commit.
  - |
    source scripts/util/get-branch.sh
    export GIT_COMMIT=$(git rev-parse HEAD)
  # Update the git branch used.
  - |
    echo "Using $GIT_BRANCH..."
    envsubst < tests/drupal-project/package.envsubst.json > tests/drupal-project/package.json
    cat tests/drupal-project/package.json
  - composer create-project drunomics/drupal-project:"dev-test#$GIT_COMMIT" --repository=tests/drupal-project/package.json project

script:
  - cd project && vendor/bin/phapp setup localdev
  - docker-compose up -d
  - docker-compose exec cli phapp install --no-build
  - curl -v http://example.project.localdev.space | grep "Drupal 8"

after_success:
  - echo "SUCCESS!"
